"""Initial migration.

Revision ID: 65b6a0c49b1b
Revises: 
Create Date: 2021-03-21 15:24:22.763787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65b6a0c49b1b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('day',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('humidity', sa.Integer(), nullable=True),
    sa.Column('icon', sa.String(length=10), nullable=True),
    sa.Column('icon_wind', sa.String(length=50), nullable=True),
    sa.Column('moon_phases_icon', sa.Integer(), nullable=True),
    sa.Column('moonrise', sa.Time(), nullable=True),
    sa.Column('moonset', sa.Time(), nullable=True),
    sa.Column('sunrise', sa.Time(), nullable=True),
    sa.Column('sunset', sa.Time(), nullable=True),
    sa.Column('temperature_max', sa.Integer(), nullable=True),
    sa.Column('temperature_min', sa.Integer(), nullable=True),
    sa.Column('text', sa.String(length=120), nullable=True),
    sa.Column('wind', sa.Integer(), nullable=True),
    sa.Column('wind_direction', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hour',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('day_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('hour_data', sa.Time(), nullable=True),
    sa.Column('humidity', sa.Integer(), nullable=True),
    sa.Column('icon', sa.String(length=10), nullable=True),
    sa.Column('icon_wind', sa.String(length=50), nullable=True),
    sa.Column('pressure', sa.Integer(), nullable=True),
    sa.Column('temperature', sa.Integer(), nullable=True),
    sa.Column('text', sa.String(length=120), nullable=True),
    sa.Column('wind', sa.Integer(), nullable=True),
    sa.Column('wind_direction', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['day_id'], ['day.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hour')
    op.drop_table('day')
    # ### end Alembic commands ###
